name: Push Pack

on:
    push:
        paths:
            - "manifest.json"

jobs:
  build:
    name: Compress, Build, and Send Pack
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Get latest pack URL
      id: java_pack_info
      run: |
        JAVA_PACK_URL=$(curl -sL https://api.github.com/repos/Coasters-Crafters/resource-pack/releases | jq -r '.[0].assets[-1].browser_download_url')
        echo "::set-output name=JAVA_PACK_URL::${JAVA_PACK_URL}"
        JAVA_PACK_FILE=$(jq -r -n --arg java_pack_url ${JAVA_PACK_URL} '$java_pack_url | split("/") | .[-1]')
        echo "::set-output name=JAVA_PACK_FILE::${JAVA_PACK_FILE}"
    - name: Set minecraft version
      id: minecraft_version
      run: |
        MINECRAFT_VERSION=1.18.2
        echo "::set-output name=MINECRAFT_VERSION::${MINECRAFT_VERSION}"
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Enable default asset cache
      id: cache-default-assets
      uses: actions/cache@v3
      with:
        path: /home/runner/work/resource-pack-bedrock/resource-pack-bedrock/staging/default_assets.zip
        key: ${{ runner.os }}-v2-${{ steps.minecraft_version.outputs.MINECRAFT_VERSION }}
    - name: Enable node module cache
      id: cache-npm
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        path: /opt/hostedtoolcache/node/**/x64/lib/node_modules
        key: ${{ runner.os }}-cache-key
    - name: Compress and stage base pack
      run: | 
        zip -8 -r -X coaster_con_base.mcpack * -x "./staging/*"
        mkdir -p staging
        cp coaster_con_base.mcpack staging/
    - name: Install NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 17
    - name: Install dependencies
      run: |
        sudo apt-get install -y moreutils zip
        yarn global add spritesheet-js
    - name: Build pack
      continue-on-error: true
      env:
        JAVA_PACK_URL: ${{ steps.java_pack_info.outputs.JAVA_PACK_URL }}
        JAVA_PACK_FILE: ${{ steps.java_pack_info.outputs.JAVA_PACK_FILE }}
        MINECRAFT_VERSION: ${{ steps.minecraft_version.outputs.MINECRAFT_VERSION }}
      run: |
        cd staging
        wget ${JAVA_PACK_URL}
        wget https://raw.githubusercontent.com/Kas-tle/java2bedrock.sh/main/converter.sh
        chmod +x converter.sh
        ./converter.sh ${JAVA_PACK_FILE} -w "false" -m "coaster_con_base.mcpack" -a "entity_alphatest_one_sided" -b "alpha_test" -f "null" -v "${MINECRAFT_VERSION}"
    - name: Archive debug artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Debugging Artifacts
        path: |
          staging/
          !staging/default_assets.zip

